[env]
DEFMT_LOG = "trace"
TROUBLE_HOST_DEFAULT_PACKET_POOL_MTU = "531"

[alias]
xrun = "run --quiet --package xtask -- run"
xattach = "run --quiet --package xtask -- attach"
xbuild = "run --quiet --package xtask -- build"
xflash = "run --quiet --package xtask -- flash"
